import Head from 'next/head';
import { Auth, ThemeSupa } from '@supabase/auth-ui-react';
import { useSession, useSupabaseClient } from '@supabase/auth-helpers-react';
import Link from 'next/link';
import Hero from '../components/home/Hero';
import Cta from '../components/home/Cta';

export default function Home() {
  const session = useSession();
  const supabase = useSupabaseClient();

  return (
    <div className='flex min-h-[calc(100vh-65px)] flex-col items-center'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {!session ? (
        <section className='mx-auto flex h-[calc(100vh-65px)] flex-col items-center justify-center'>
          <Auth
            supabaseClient={supabase}
            appearance={{
              theme: ThemeSupa,
              // this is where custom classes would go
              /* className: {
                button: 'bg-brand-500',
              }, */
            }}
          />
        </section>
      ) : (
        <>
          <Hero />
          <Cta />
        </>
      )}
    </div>
  );
}
